// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ddosmitigator

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdpDropLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

// loadXdpDrop returns the embedded CollectionSpec for xdpDrop.
func loadXdpDrop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpDropBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdpDrop: %w", err)
	}

	return spec, err
}

// loadXdpDropObjects loads xdpDrop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpDropObjects
//	*xdpDropPrograms
//	*xdpDropMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpDropObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdpDrop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpDropSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpDropSpecs struct {
	xdpDropProgramSpecs
	xdpDropMapSpecs
	xdpDropVariableSpecs
}

// xdpDropProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpDropProgramSpecs struct {
	XdpDdosDrop *ebpf.ProgramSpec `ebpf:"xdp_ddos_drop"`
}

// xdpDropMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpDropMapSpecs struct {
	JailMap  *ebpf.MapSpec `ebpf:"jail_map"`
	StatsMap *ebpf.MapSpec `ebpf:"stats_map"`
}

// xdpDropVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpDropVariableSpecs struct {
}

// xdpDropObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpDropObjects struct {
	xdpDropPrograms
	xdpDropMaps
	xdpDropVariables
}

func (o *xdpDropObjects) Close() error {
	return _XdpDropClose(
		&o.xdpDropPrograms,
		&o.xdpDropMaps,
	)
}

// xdpDropMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpDropMaps struct {
	JailMap  *ebpf.Map `ebpf:"jail_map"`
	StatsMap *ebpf.Map `ebpf:"stats_map"`
}

func (m *xdpDropMaps) Close() error {
	return _XdpDropClose(
		m.JailMap,
		m.StatsMap,
	)
}

// xdpDropVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpDropVariables struct {
}

// xdpDropPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpDropPrograms struct {
	XdpDdosDrop *ebpf.Program `ebpf:"xdp_ddos_drop"`
}

func (p *xdpDropPrograms) Close() error {
	return _XdpDropClose(
		p.XdpDdosDrop,
	)
}

func _XdpDropClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpdrop_x86_bpfel.o
var _XdpDropBytes []byte
